### ISSUE TITLE
It is recommended to add the state before death inheritance

### ISSUE THREAD

**Issue by xiaozhiyl** [ShaneBeeStudios/SurvivalPlus#18]
Can this add a state that will be inherited after death and rebirth? Otherwise, as long as the player has no state, he will kill himself and fill the state

**Comment by ShaneBeee** [comment]
what do you mean a state?

**Comment by xiaozhiyl** [comment]
Can this add a state that will be inherited before death after rebirth? Otherwise, as long as there is no status, you will choose to commit suicide

**Comment by xiaozhiyl** [comment]
For example, if the energy or hunger and thirst value has been exhausted, the player will commit suicide and then these energy or hunger and thirst values will be reset and filled. So can you add death and inherit the state before death?

**Comment by ShaneBeee** [comment]
This isn't really possible to do.
If the player died due to exhaustion, then they player would respawn with the same energy level, and die again, then respawn again then die again.

As of right now you can change the respawn amount for hunger and thirst. Ill make changes so you can also change how much energy and nutrition values a player will get on respawn.
